import * as typeScript from "typescript"

const output: typeScript.CompilerOptions = {
  allowJs: false,
  allowSyntheticDefaultImports: false,
  allowUmdGlobalAccess: false,
  allowUnreachableCode: false,
  allowUnusedLabels: false,
  alwaysStrict: false,
  baseUrl: ``,
  charset: `utf8`,
  //checkJs: true,
  composite: false,
  declaration: true,
  declarationMap: false,
  diagnostics: false,
  disableSizeLimit: false,
  downlevelIteration: false,
  emitBOM: false,
  emitDeclarationOnly: false,
  emitDecoratorMetadata: false,
  esModuleInterop: false,
  experimentalDecorators: false,
  forceConsistentCasingInFileNames: true,
  importHelpers: false,
  incremental: false,
  inlineSourceMap: false,
  inlineSources: false,
  isolatedModules: false,
  jsx: typeScript.JsxEmit.None,
  //jsxFactory: ,
  keyofStringsOnly: false,
  lib: [
    `dom`,
    `es5`,
    `scripthost`
  ],
  listEmittedFiles: false,
  listFiles: false,
  //mapRoot: ,
  maxNodeModuleJsDepth: 0,
  module: typeScript.ModuleKind.None,
  moduleResolution: typeScript.ModuleResolutionKind.Classic,
  // newLine: ,
  noEmit: false,
  noEmitHelpers: true,
  noEmitOnError: true,
  noErrorTruncation: true,
  noFallthroughCasesInSwitch: true,
  noImplicitAny: true,
  noImplicitReturns: true,
  noImplicitThis: true,
  noImplicitUseStrict: true,
  noLib: false,
  noResolve: false,
  noStrictGenericChecks: false,
  noUnusedLocals: true,
  noUnusedParameters: true,
  //outDir: ,
  outFile: `result.js`,
  //paths: {},
  preserveConstEnums: false,
  preserveSymlinks: false,
  preserveWatchOutput: true,
  pretty: true,
  //reactNamespace: React,
  removeComments: true,
  resolveJsonModule: false,
  //rootDir: ,
  //rootDirs: [],
  skipDefaultLibCheck: false,
  skipLibCheck: false,
  sourceMap: false,
  //sourceRoot: ,
  strict: false,
  strictBindCallApply: true,
  strictFunctionTypes: true,
  strictPropertyInitialization: true,
  strictNullChecks: true,
  suppressExcessPropertyErrors: false,
  suppressImplicitAnyIndexErrors: false,
  target: typeScript.ScriptTarget.ES3,
  traceResolution: false,
  tsBuildInfoFile: undefined,
  types: [],
  typeRoots: []
}

export default output
